export const refs = {
  gallery: document.querySelector('.gallery'),
  form: document.querySelector('.navigation__form'),
  notificate: document.querySelector('.navigation__notificate'),
  backdrop: document.querySelector('.js-backdrop'),
  watchButton: document.querySelector('.button-watched__modal'),
  queueButton: document.querySelector('.button-queue__modal'),
  modal: document.querySelector('.modal__content'),
  closeModalBtn: document.querySelector('.modal-close'),
  buttonsContainer: document.querySelector('.buttons-modal'),
  queueBtnLib: document.querySelector('.button-queue'),
  watchedBtnLib: document.querySelector('.button-watched'),
  galleryLib: document.querySelector('.gallery-lib'),
  fillerContainer: document.querySelector('.filler-container'),
};
