export const refs = {
  gallery: document.querySelector('.gallery'),
  form: document.querySelector('.navigation__form'),
  notificate: document.querySelector('.navigation__notificate'),
  backdrop: document.querySelector('.js-backdrop'),
  watchButton: document.querySelector('.button-watched__modal'),
  queueButton: document.querySelector('.button-queue__modal'),
  modal: document.querySelector('.modal__content'),
  closeModalBtn: document.querySelector('.modal-close'),
  buttonsContainer: document.querySelector('.buttons-modal'),
  queueBtnLib: document.querySelector('.button-queue'),
  watchedBtnLib: document.querySelector('.button-watched'),
  galleryLib: document.querySelector('.gallery-lib'),
  // login refs
  logoutButton: document.querySelector('.logout'),
  userImg: document.querySelector('.user__img'),
  userName: document.querySelector('.user__name'),
  userInfo: document.querySelector('.user-info'),
  signupButton: document.querySelector('.signup_button'),
  loginForm: document.querySelector('.login'),
  singupForm: document.querySelector('.signup'),
  loginGoogle: document.querySelector('.login_google'),
  signupGoogle: document.querySelector('.signup_google'),
  signupOpen: document.querySelector('.signup-button-open'),
  loginOpen: document.querySelector('.login-button-open'),
  authButtList: document.querySelector('.auth__button-list'),
};
